# Generated by Django 6.0 on 2025-12-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
